version: "3.9"
services:
  db:
    container_name: db_java
    image: mysql:latest
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_java
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    ports:
      - 8081:80